Feature/#20 board update channel delete
Team-4IGHTING/4Gamer-Client pull request #22
Opened 2024-08-12 05:50 UTC by taeaeaeae

# 개요

채널 관리자페이지 미완성 된 부분 추가

# 작업사항

- [x] 게시판 수정
- [x] 채널 삭제
- [x] 블랙리스트 param으로 채널아이디 받음

# 관련 이슈

- close #20

2024-08-12 07:51 UTC, hellou8363 approved these changes
확인했습니다.

2024-08-12 07:51 UTC, hellou8363 commented on src/api/channelApi.ts
> +export const deleteChannel = async (channelId: any) => {
타입을 any로 바꾸는 이유가 있나요?

2024-08-12 08:00 UTC, taeaeaeae commented on src/api/channelApi.ts
> +export const deleteChannel = async (channelId: any) => {
param에서 받아오니까 number로 인식하려면 타입을 변환해줘야되는데 변환 대신 any로 바꿨습니다.

2024-08-12 11:50 UTC, KangBaekho10 approved these changes
확인했습니다.

2024-08-13 01:30 UTC, Turbstructor requested changes
`LoginContainer` 쪽에 확인 부탁드립니다!

2024-08-13 01:30 UTC, Turbstructor commented on src/components/LoginContainer.tsx
> +    window.location.href = `https://4-gamer.store/oauth2/authorization/google`;
여기에 있는 `window.location.href`를 환경변수에서 받아오는 걸로 변경해주실 수 있나요?

2024-08-13 01:37 UTC, taeaeaeae commented on src/components/LoginContainer.tsx
> +    window.location.href = `https://4-gamer.store/oauth2/authorization/google`;
수정했습니다

2024-08-13 01:39 UTC, Turbstructor approved these changes
확인했습니다.

2024-08-13 01:39 UTC, merged